/**
 * api/_lib/trip.js
 * Shared by the group-trip API and the Stripe webhook:
 *  - quote():  the server-side price estimate for a group trip (browser prices are never trusted)
 *  - email helpers: branded HTML for guest and business notifications
 *  - stripeRequest(): thin Stripe REST helper (kept on the module object so tests can stub it)
 */

const https = require('https');
const querystring = require('querystring');

let CATALOG = { items: {}, transfers: {} };
try { CATALOG = require('../_data/builder-catalog.json'); } catch (e) { /* generated by build.js */ }

const MIN_GUESTS = 5;
const MAX_GUESTS = 60;
const VAN_CAPACITY = 6;          // one transfer vehicle seats up to 6
const DEPOSIT_RATE = 0.25;       // share of the estimate taken as a deposit
const DEPOSIT_MIN = 100;         // dollars
const STRIPE_PCT = 0.029;        // card fee passed through so the deposit nets in full
const STRIPE_FIXED = 0.30;

const AUDIENCES = { mba: 'MBA Lifestyle', greek: 'Greek Life' };

function esc(x) {
  return String(x == null ? '' : x)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
function money(n) {
  return '$' + Number(n || 0).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
}
function round2(n) { return Math.round(n * 100) / 100; }

/**
 * Price a group trip. `input`: { country, guests, items: [title], transfers: bool }
 * Returns { ok:true, ... } or { ok:false, error }.
 */
function quote(input) {
  input = input || {};
  const country = String(input.country || '');
  const guests = parseInt(input.guests, 10);
  if (!(guests >= MIN_GUESTS && guests <= MAX_GUESTS)) {
    return { ok: false, error: 'Group size must be between ' + MIN_GUESTS + ' and ' + MAX_GUESTS + ' guests.' };
  }
  if (!country || !CATALOG.transfers[country]) return { ok: false, error: 'Please choose an island.' };

  const titles = Array.isArray(input.items) ? input.items.map(String) : [];
  if (titles.length > 30) return { ok: false, error: 'Please choose 30 experiences or fewer.' };

  const lines = [];
  let subtotal = 0, onRequest = 0;
  const seen = new Set();
  for (const title of titles) {
    if (seen.has(title)) continue;
    seen.add(title);
    const it = CATALOG.items[title];
    if (!it || it.country !== country) return { ok: false, error: 'Unknown experience: ' + title };
    if (!(it.price > 0)) { lines.push({ title, area: it.area, unit: 'request', price: 0, qty: 0, amount: 0 }); onRequest++; continue; }
    let qty, unit;
    if (it.per === 'group') { unit = 'group'; qty = it.cap ? Math.ceil(guests / it.cap) : 1; }
    else { unit = 'person'; qty = guests; }
    const amount = round2(it.price * qty);
    lines.push({ title, area: it.area, unit, price: it.price, qty, amount });
    subtotal += amount;
  }

  let transfers = null;
  if (input.transfers === true || input.transfers === 'true') {
    const tr = CATALOG.transfers[country];
    const perGuest = /guest/i.test(tr.per || '');
    const qty = perGuest ? guests : Math.ceil(guests / VAN_CAPACITY);
    const amount = round2(tr.price * qty);
    transfers = { name: 'Private airport & inter-base transfers', unit: perGuest ? 'guest' : 'vehicle', price: tr.price, qty, amount };
    subtotal += amount;
  }
  subtotal = round2(subtotal);

  let deposit = null;
  if (subtotal > 0) {
    const base = Math.min(subtotal, Math.max(DEPOSIT_MIN, Math.ceil(subtotal * DEPOSIT_RATE)));
    const charge = Math.ceil(((base + STRIPE_FIXED) / (1 - STRIPE_PCT)) * 100) / 100;
    deposit = { rate: DEPOSIT_RATE, amount: base, fee: round2(charge - base), charge, chargeCents: Math.round(charge * 100) };
  }
  return {
    ok: true, country, guests, lines, transfers, subtotal, onRequest,
    perPerson: guests ? round2(subtotal / guests) : 0,
    deposit
  };
}

/* ---------- validation helpers ---------- */
function cleanContact(c) {
  c = c || {};
  const name = String(c.name || '').trim().slice(0, 80);
  const email = String(c.email || '').trim().toLowerCase().slice(0, 120);
  const phone = String(c.phone || '').trim().slice(0, 40);
  if (name.length < 2) return { error: 'Please add your name.' };
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) return { error: 'Please add a valid email address.' };
  return { name, email, phone };
}
function cleanPrefs(p) {
  p = p || {};
  const list = (Array.isArray(p.interests) ? p.interests : []).map(x => String(x).trim().slice(0, 30)).filter(Boolean).slice(0, 10);
  return {
    month: String(p.month || '').trim().slice(0, 40),
    budget: String(p.budget || '').trim().slice(0, 40),
    interests: list,
    notes: String(p.notes || '').trim().slice(0, 1500)
  };
}
function ref(prefix) {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let s = '';
  for (let i = 0; i < 6; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return prefix + '-' + s;
}

/* ---------- email html ---------- */
function summaryTable(q, opts) {
  opts = opts || {};
  const rows = q.lines.map((l, i) => {
    const bg = i % 2 ? ' style="background:#f6faf7"' : '';
    let right;
    if (l.unit === 'request') right = 'Price on request';
    else if (l.unit === 'group') right = money(l.amount) + (l.qty > 1 ? ' (' + l.qty + ' boats)' : ' (per group)');
    else right = money(l.amount) + ' <span style="color:#8a97a2">(' + money(l.price) + ' × ' + l.qty + ')</span>';
    return `<tr${bg}><td style="padding:8px 9px;color:#333">${esc(l.title)}<div style="color:#8a97a2;font-size:11px">${esc(l.area || '')}</div></td><td style="padding:8px 9px;color:#333;text-align:right;white-space:nowrap">${right}</td></tr>`;
  }).join('');
  const tr = q.transfers
    ? `<tr><td style="padding:8px 9px;color:#333">${esc(q.transfers.name)}</td><td style="padding:8px 9px;color:#333;text-align:right;white-space:nowrap">${money(q.transfers.amount)} <span style="color:#8a97a2">(${q.transfers.qty} ${q.transfers.unit}${q.transfers.qty > 1 ? 's' : ''})</span></td></tr>` : '';
  const empty = !q.lines.length && !q.transfers
    ? '<tr><td style="padding:8px 9px;color:#8a97a2" colspan="2">No experiences chosen yet — we will help you shape this together.</td></tr>' : '';
  return `<table style="border-collapse:collapse;width:100%;margin:8px 0 14px">${rows}${tr}${empty}
    <tr><td style="padding:10px 9px;border-top:2px solid #063a63;font-weight:bold;color:#063a63">Estimated total</td>
    <td style="padding:10px 9px;border-top:2px solid #063a63;text-align:right;font-weight:bold;color:#063a63">${money(q.subtotal)}${q.guests ? ' <span style="color:#8a97a2;font-weight:normal">(≈ ' + money(q.perPerson) + ' per person)</span>' : ''}</td></tr>
  </table>`;
}
function detailTable(rows) {
  return `<table style="border-collapse:collapse;width:100%;margin:8px 0 16px">${rows.filter(r => r[1]).map((r, i) =>
    `<tr${i % 2 ? ' style="background:#f6faf7"' : ''}><td style="padding:8px 9px;font-weight:bold;width:150px;color:#063a63;vertical-align:top">${esc(r[0])}</td><td style="padding:8px 9px;color:#333;white-space:pre-wrap">${esc(r[1])}</td></tr>`).join('')}</table>`;
}
function shell(heading, bodyHtml) {
  return `
  <div style="font-family:sans-serif;max-width:620px;margin:0 auto">
    <div style="background:linear-gradient(135deg,#063a63,#0a5678);color:#fff;padding:26px 24px;border-radius:16px 16px 0 0">
      <div style="font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#70c257;font-weight:800">Sight Seers Caribbean Adventures</div>
      <h2 style="margin:8px 0 0;font-size:22px">${esc(heading)}</h2>
    </div>
    <div style="border:1px solid #e0e7e3;border-top:none;border-radius:0 0 16px 16px;padding:24px;color:#5a6d7e;font-size:14px;line-height:1.65">
      ${bodyHtml}
      <div style="margin-top:18px;padding:14px 16px;background:rgba(112,194,87,.08);border-radius:12px;color:#063a63;font-size:13px"><b>Sight Seers Caribbean Adventures</b><br>+1 (876) 465-0630 · info@sightseerscaribbean.com</div>
    </div>
    <p style="color:#9aa7b2;font-size:11px;text-align:center;margin-top:14px">Estimates use “from” prices and are confirmed by our team. Villa stays, meals and gratuities are quoted separately.</p>
  </div>`;
}
function tripRows(rec) {
  const p = rec.prefs || {};
  return [
    ['Reference', rec.ref],
    ['Group', (AUDIENCES[rec.audience] || rec.audience) + ' · ' + rec.guests + ' guests'],
    ['Island', rec.country],
    ['Travel month', p.month],
    ['Budget', p.budget],
    ['Interests', (p.interests || []).join(', ')],
    ['Notes', p.notes]
  ];
}

function stripeRequest(method, path, params) {
  return new Promise((resolve, reject) => {
    const payload = params ? querystring.stringify(params) : null;
    const req = https.request({
      hostname: 'api.stripe.com', path, method,
      headers: Object.assign({
        'Authorization': 'Bearer ' + process.env.STRIPE_SECRET_KEY,
        'Content-Type': 'application/x-www-form-urlencoded'
      }, payload ? { 'Content-Length': Buffer.byteLength(payload) } : {})
    }, (res) => {
      let data = '';
      res.on('data', d => data += d);
      res.on('end', () => { try { resolve({ status: res.statusCode, body: JSON.parse(data) }); } catch (e) { resolve({ status: res.statusCode, body: data }); } });
    });
    req.on('error', reject);
    if (payload) req.write(payload);
    req.end();
  });
}

module.exports = {
  CATALOG, MIN_GUESTS, MAX_GUESTS, VAN_CAPACITY, DEPOSIT_RATE, DEPOSIT_MIN, AUDIENCES,
  quote, cleanContact, cleanPrefs, ref, esc, money, summaryTable, detailTable, shell, tripRows, stripeRequest
};
