/**
 * api/_handlers/group-trip.js
 * Group trip builder backend (MBA Lifestyle / Greek Life, groups of 5+).
 *
 *   POST { action:'checkout' }     price the trip on the server, store it, return a Stripe Checkout URL for the deposit
 *   POST { action:'preferences' }  save a guest's trip preferences and email a copy to them and to the team
 *   POST { action:'consult' }      request a consultation to personalise the trip
 *   GET  (admin)                   list stored trips, preferences and consultations
 *
 * Prices always come from api/_data/builder-catalog.json (generated by build.js from the site's own
 * experience list). Anything the browser claims about price is ignored.
 */

const db = require('../_lib/db');
const { uid, requireAdmin } = require('../_lib/auth');
const { sendEmail, BUSINESS_EMAIL } = require('../_lib/email');
const trip = require('../_lib/trip');

const SITE = 'https://sightseerscaribbean.com';
function safeOrigin(h) {
  const o = String((h && h.origin) || '');
  return /^https:\/\/([a-z0-9-]+\.)*(sightseerscaribbean\.com|vercel\.app)$/i.test(o) ? o : SITE;
}

function prepare(b, { needItems } = {}) {
  const audience = String(b.audience || '');
  if (!trip.AUDIENCES[audience]) return { error: 'Please choose a group type.' };
  const contact = trip.cleanContact(b.contact);
  if (contact.error) return { error: contact.error };
  const q = trip.quote({ country: b.country, guests: b.guests, items: b.items, transfers: b.transfers });
  if (!q.ok) return { error: q.error };
  if (needItems && !q.lines.some(l => l.amount > 0)) return { error: 'Add at least one priced experience before reserving.' };
  return { audience, contact, q, prefs: trip.cleanPrefs(b.prefs) };
}

function publicQuote(q) {
  return {
    guests: q.guests, subtotal: q.subtotal, perPerson: q.perPerson, onRequest: q.onRequest,
    deposit: q.deposit ? { amount: q.deposit.amount, fee: q.deposit.fee, charge: q.deposit.charge } : null
  };
}

function record(kind, refPrefix, p, b, extra) {
  return Object.assign({
    id: uid(),
    ref: trip.ref(refPrefix),
    kind,
    audience: p.audience,
    country: p.q.country,
    guests: p.q.guests,
    items: p.q.lines.map(l => l.title),
    transfers: !!p.q.transfers,
    quote: p.q,
    contact: p.contact,
    prefs: p.prefs,
    createdAt: new Date().toISOString()
  }, extra || {});
}

async function notify(rec, { subject, heading, guestIntro, bizIntro, extraRows }) {
  const summary = trip.summaryTable(rec.quote);
  const rows = trip.tripRows(rec).concat(extraRows || []);
  const contactRows = [['Name', rec.contact.name], ['Email', rec.contact.email], ['Phone / WhatsApp', rec.contact.phone]];
  await Promise.all([
    sendEmail({
      to: rec.contact.email,
      replyTo: BUSINESS_EMAIL,
      subject,
      html: trip.shell(heading, `<p>${guestIntro}</p>${trip.detailTable(rows)}<h3 style="color:#063a63;margin:4px 0 0;font-size:16px">Your selections</h3>${summary}`)
    }),
    sendEmail({
      replyTo: rec.contact.email,
      subject: '[' + rec.ref + '] ' + subject,
      html: trip.shell(heading, `<p>${bizIntro}</p>${trip.detailTable(contactRows.concat(rows))}<h3 style="color:#063a63;margin:4px 0 0;font-size:16px">Selections</h3>${summary}`)
    })
  ]);
}

module.exports = async function handler(req, res) {
  try {
    if (req.method === 'OPTIONS') return res.status(200).end();

    if (req.method === 'GET') {
      const admin = requireAdmin(req, res);
      if (!admin) return;
      const [trips, preferences, consultations] = await Promise.all([
        db.getCollection('group-trips'), db.getCollection('trip-preferences'), db.getCollection('trip-consultations')
      ]);
      return res.status(200).json({ ok: true, trips, preferences, consultations });
    }
    if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

    const b = req.body || {};
    if (b.website) return res.status(200).json({ ok: true });          // honeypot
    const action = String(b.action || '');

    /* ---------- deposit checkout ---------- */
    if (action === 'checkout') {
      if (!process.env.STRIPE_SECRET_KEY) return res.status(500).json({ error: 'Online payments are not configured yet. Please send an inquiry instead.' });
      const p = prepare(b, { needItems: true });
      if (p.error) return res.status(400).json({ error: p.error });

      const rec = record('group-trip', 'GT', p, b, { status: 'deposit-pending', deposit: p.q.deposit });
      try { await db.addToCollection('group-trips', rec); } catch (e) { console.error('group-trip save error:', e && e.message); }

      const origin = safeOrigin(req.headers);
      const params = {
        'mode': 'payment',
        'success_url': origin + '/?booked=1&trip=' + rec.ref,
        'cancel_url': origin + '/',
        'customer_email': p.contact.email,
        'line_items[0][quantity]': '1',
        'line_items[0][price_data][currency]': 'usd',
        'line_items[0][price_data][unit_amount]': String(p.q.deposit.chargeCents),
        'line_items[0][price_data][product_data][name]': ('Group trip deposit: ' + rec.country + ' (' + rec.guests + ' guests)').slice(0, 250),
        'line_items[0][price_data][product_data][description]': ('Ref ' + rec.ref + '. Deposit toward an estimated total of ' + trip.money(p.q.subtotal) + ' (includes card processing). Balance and final itinerary are confirmed by our team.').slice(0, 500),
        'metadata[kind]': 'group-trip',
        'metadata[ref]': rec.ref,
        'metadata[audience]': rec.audience,
        'metadata[country]': rec.country,
        'metadata[guests]': String(rec.guests),
        'metadata[estimate]': String(p.q.subtotal),
        'metadata[deposit]': String(p.q.deposit.amount),
        'metadata[items]': rec.items.join('; ').slice(0, 480),
        'metadata[contact]': (p.contact.name + ' · ' + p.contact.phone).slice(0, 200)
      };
      const r = await trip.stripeRequest('POST', '/v1/checkout/sessions', params);
      if (r.status !== 200) return res.status(502).json({ error: 'Could not start checkout right now. Please try again or send an inquiry.' });
      try { await db.updateInCollection('group-trips', rec.id, { stripeSession: r.body.id }); } catch (e) { /* non-fatal */ }
      return res.status(200).json({ ok: true, url: r.body.url, ref: rec.ref, quote: publicQuote(p.q) });
    }

    /* ---------- save preferences ---------- */
    if (action === 'preferences') {
      const p = prepare(b);
      if (p.error) return res.status(400).json({ error: p.error });
      const rec = record('preferences', 'PR', p, b, { status: 'saved' });
      await db.addToCollection('trip-preferences', rec);
      await notify(rec, {
        subject: 'Your trip preferences are saved: ' + rec.ref,
        heading: 'Preferences saved',
        guestIntro: 'Thank you, ' + trip.esc(rec.contact.name.split(' ')[0]) + '. We have saved your trip preferences. A planner will use them to shape a group itinerary around you. Reply to this email any time to change something, or book a quick consultation.',
        bizIntro: 'A guest saved trip preferences on the group trip builder.'
      });
      return res.status(201).json({ ok: true, ref: rec.ref, quote: publicQuote(p.q) });
    }

    /* ---------- consultation request ---------- */
    if (action === 'consult') {
      const p = prepare(b);
      if (p.error) return res.status(400).json({ error: p.error });
      const c = b.consult || {};
      const consult = {
        channel: String(c.channel || 'Email').trim().slice(0, 30),
        when: String(c.when || '').trim().slice(0, 120),
        notes: String(c.notes || '').trim().slice(0, 1500)
      };
      const rec = record('consult', 'CN', p, b, { status: 'new', consult });
      await db.addToCollection('trip-consultations', rec);
      const extraRows = [['Preferred contact', consult.channel], ['Best times', consult.when], ['What they want to discuss', consult.notes]];
      await notify(rec, {
        subject: 'Your consultation request: ' + rec.ref,
        heading: 'Consultation requested',
        guestIntro: 'Thank you, ' + trip.esc(rec.contact.name.split(' ')[0]) + '. We have your request and a trip planner will be in touch within one business day to personalise your group trip.',
        bizIntro: 'A guest asked for a consultation to personalise a group trip (' + trip.esc(String(rec.guests)) + ' guests).',
        extraRows
      });
      return res.status(201).json({ ok: true, ref: rec.ref });
    }

    return res.status(400).json({ error: 'Invalid action' });
  } catch (err) {
    console.error('Group trip error:', err && err.message, err && err.stack);
    return res.status(500).json({ error: 'Something went wrong. Please try again, or send us an inquiry.' });
  }
};
